version: '3'

services:
  app:
    build: .
    image: employees_app
    environment:
      MONGO_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db:27017
    command: uvicorn app.main:app --host ${HOST} --port ${PORT}
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - db

  app_tests:
    build: .
    image: employees_app
    environment:
      MONGO_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db:27017
    command: pytest tests
    depends_on:
      - db

  db:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - ./data/employees.json:/tmp/employees.json
      - ./data/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 127.0.0.1:27017:27017
